import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
            Hostel Mate
        </div>
        <div className={styles.sidebar}>
          {
            pages.map((item,i)=>{
              return (
                <div className={styles.sideitem}>

                <Link href={item.ref} >{item.title}</Link>
                </div>
              )
            })
          }

        
        </div>

      </main>
    </>
  )
}



const pages = [
  {
    title:"Entry",
    ref:"/"
  },
  {
    title:"Application",
    ref:"/app/application"
  },
  {
    title:"Fees",
    ref:"/"
  }
]